# Generated by Django 5.0.6 on 2024-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_participant_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
